### ISSUE TITLE
Bones bug

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#196]
when creating bones:

Error: After Effects error: Unable to call "addSolid" because of parameter 3. Value 0 out of range 1 to 30000.

**Comment by joorce** [comment]
Hi
I can confirm that I have the same issue. It's related with the size of the bones. I "fixed" changing the size of the bones in the settings panel. I guess that the script, if using autosize, should check for under zero layer sizes.

**Comment by Nico-Duduf** [comment]
fixed

**Comment by nicolevenuto** [comment]
I'm with this problem, I don't know what size I should put on bones settings to fix this issue

**Comment by Nico-Duduf** [comment]
Hi, 
Did you update Duik to the latest version? 
This should be fixed. 
If you use the latest, 15.11,there may still be a bug somewhere...

**Comment by nicolevenuto** [comment]
Yes, that's the version I have

**Comment by Nico-Duduf** [comment]
And you have this same error? 
I'll have to investigate... 

What version of After Effects and what OS do you use?

**Comment by nicolevenuto** [comment]
Hey,  I fixed
My After Effects is CC 2015 for windows, I adjusted the size of my layer, a bit bigger than before and worked, thanks

**Comment by Nico-Duduf** [comment]
OK, 
Thanks for your feedback. 



Le 16 oct. 2016 22:10, à 22:10, Nicole <notifications@github.com> a écrit:

**Comment by Nico-Duduf** [comment]
fixed, available in the update in a few days
