### ISSUE TITLE
IK on one layer+goal not working

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#199]
does nothing

**Comment by kbo1358** [comment]
Is there an update on this bug? I am also seeing that 1-layer IK + Goal does nothing.

**Comment by Nico-Duduf** [comment]
Not yet, it's planned for Duik 16
A simple workaround is to first create the IK, selecting the "limb" and the controller only, then create the IK Goal, selecting the end and the controller.

**Comment by Nico-Duduf** [comment]
fixed, available in the update in a few days
