### ISSUE TITLE
Check update block AE GUI for too long

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/Duik#220]
Many of us can't access your website (it's not you fault), so it takes a long time waiting request and blocking AE's GUI as if crashed.
So could there be a message dialog to let us know when checking update, even a checkbox to disable auto-update when first time we boot the script?
Thanks

**Comment by Nico-Duduf** [comment]
There is a checkbox in the settings panel of Duik to disable auto-update;
You're right, I'll definitely have to change the way Duik shows a progress bar or anything else to let the user know when it's working...
I think I'm going to entirely update the UI in Duik 16, using the new CEP Panels, this will fix a lot of UI issues/freezes and improve stability
