### ISSUE TITLE
Script Alert can't be translate

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/Duik#225]
It seems that many "throw <message>" in libduik.jsxinc don't read translation file. So I can't translate it. Is there any walkaround solution?
Thanks!

**Comment by Nico-Duduf** [comment]
No solution yet!
I began to add some "throw" expressions in libduik for developpers who want to use the library, I think it's more friendly if there are some errors when using the functions, but those strings are not meant to be used in Duik's User Interface, so I don't think there's a need for translation.
All developpers do understand English, don't they? ;)

**Comment by eZioPan** [comment]
OK, thx~
