### ISSUE TITLE
AE CS6 Plantigrade asking for tail nulls

### ISSUE THREAD

**Issue by DhatesCode** [Rainbox-dev/Duik#226]
I just started using Duik, and the first character I tried to rig it's demanding I select nulls for a tail, even though I'm using Plantigrade. I got around this by making temporary puppet pins, doing the auto-rig and then deleting the nulls and pins.

Is this a known bug? Possibly for older AE versions?

thanks

**Comment by Nico-Duduf** [comment]
Hi,
Sorry to reply late, I was on hollidays.

It's not a bug, you can leave all the fields empty if your character has no tail, and the tail rigging will be skipped (I think this is explained in the user guide)

BTW, there are some plantigrades with tails : apes! marmots!

**Comment by DhatesCode** [comment]
That's what I thought. The problem I had is that when I do leave them blank, it will not create the rig.

**Comment by Nico-Duduf** [comment]
In this case it's a bug...
Could you send me the AEP where the autorig fails?

I'll have a look at that.

**Comment by DhatesCode** [comment]
sure thing. I'll pack them up in a bit. It might be because I'm using an old version of AE and OS X, as I said.
