### ISSUE TITLE
Duik.1DWiggle -> Uncaught ReferenceError: ease is not defined

### ISSUE THREAD

**Issue by Jeremboo** [Rainbox-dev/Duik#231]
Hi !

Thanks to after effects plugin [bodymovin](https://github.com/bodymovin/bodymovin), it is possible to export animations in JSON and use it in web application.

But, I have some trouble with your Fx Wiggle included in your library.

In fact, when I export my animation, some of your plugin code is exported : 

```
var fn = function(){var $bm_rt;
var freq, amp, loop, t, w1, w2, w;
freq = effect('Echelle Wiggle')(2);
amp = effect('Echelle Wiggle')(1);
loop = effect('Echelle Wiggle')(3);
if (loop == 0)
    loop = thisComp.duration;
t = sub(time % loop, loop);
w1 = wiggle(freq, amp, 1, 0.5, t);
w2 = wiggle(freq, amp, 1, 0.5, sub(t, loop));
w = easeIn(t, -loop, 0, w1, w2);
$bm_rt = sub(sum(w, value), valueAtTime(0));;this.v = $bm_rt;}

```

and, when I try to start my project, it returns only one error :  `Uncaught ReferenceError: ease is not defined`.

***So have you some ideas to this issue ?  Where is the `ease` function ? How can I found her ?***

I actually tried to add manually the `ease` function on the part of the code (`var ease = function(t){ return t*t }`) and the script compiles. But my shape is distorted.

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, bodymovin seems to be an awesome tool!
I didn't knew it, but I'll have a look at that and let you know if I find anything...

I read in [the readme](https://github.com/bodymovin/bodymovin/blob/master/README.md) of bodymovin that only slider/expression controls effects are supported yet, and Duik uses its own effects, it may be an issue when exporting your animation.

You can try to populate all vars at the beginning of the exported function by the actual values of the wiggle effect on the corresponding layer ; something like that:
`var fn = function(){var $bm_rt;
var freq, amp, loop, t, w1, w2, w;
freq = yourFrequencyValue;
amp = yourAmplitudeValue;
loop = yourLoopDurationInSeconds;
if (loop == 0)
    loop = thisComp.duration;
t = sub(time % loop, loop);
w1 = wiggle(freq, amp, 1, 0.5, t);
w2 = wiggle(freq, amp, 1, 0.5, sub(t, loop));
w = easeIn(t, -loop, 0, w1, w2);
$bm_rt = sub(sum(w, value), valueAtTime(0));;this.v = $bm_rt;}`

I just read in the [wiki](https://github.com/bodymovin/bodymovin/wiki/Expressions) that the wiggle() function is unsupported too

(actually, I'm thinking about including bodymovin in Duik itself, if its license allow it)
Thanks for your feedback, bodymovin seems to be an awesome tool!
I didn't knew it, but I'll have a look at that and let you know if I find anything...

I read in [the readme](https://github.com/bodymovin/bodymovin/blob/master/README.md) of bodymovin that only slider/expression controls effects are supported yet, and Duik uses its own effects, it may be an issue when exporting your animation.

You can try to populate all vars at the beginning of the exported function by the actual values of the wiggle effect on the corresponding layer ; something like that:
`var fn = function(){var $bm_rt;
var freq, amp, loop, t, w1, w2, w;
freq = yourFrequencyValue;
amp = yourAmplitudeValue;
loop = yourLoopDurationInSeconds;
if (loop == 0)
    loop = thisComp.duration;
t = sub(time % loop, loop);
w1 = wiggle(freq, amp, 1, 0.5, t);
w2 = wiggle(freq, amp, 1, 0.5, sub(t, loop));
w = easeIn(t, -loop, 0, w1, w2);
$bm_rt = sub(sum(w, value), valueAtTime(0));;this.v = $bm_rt;}`

I just read in the [wiki](https://github.com/bodymovin/bodymovin/wiki/Expressions) that the `wiggle()` function is unsupported too, unfortunately you have to reimplement it in the exported JavaScript...

Anyway, I don't understand the error returned, there's nothing about something called "ease" in this expression ;)
Maybe the easeIn() function is unsupported too, but it's not exactly called "ease"...

(actually, I'm thinking about including bodymovin in Duik itself, if its license allow it)

**Comment by Jeremboo** [comment]
Hi ! 

Thx for your report (be careful your message is duplicated).

Sorry, but I made a mistake into my issue about ease function :  `easeIn` does not exist. That's `ease` sorry.

Indeed, I think I must reimplement the `ease` and `wiggle` functions and the values of the variables. But for now, this doesn't make good... I prefer to delete this effect for the moment.

Good luck for the next !

**Comment by Nico-Duduf** [comment]
Sorry for the duplicate, that's what happens when trying to post from a "smart"phone ;)
