### ISSUE TITLE
Language Choose before Setup Script

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/Duik#234]
If user put script in ScriptUI Panel, they will read English version install instruction. Could there be language choose at first screen rather than the settings?

**Comment by Nico-Duduf** [comment]
good suggestion!
I'll do that in the next update

**Comment by kevinmasson** [comment]
Je suis en train de jeter un oeil pour cette fonctionnalité :)

**Comment by Nico-Duduf** [comment]
C'est ce que j'aurais fait aussi !

**Comment by Nico-Duduf** [comment]
done
