### ISSUE TITLE
Multiplan 2D layers' names

### ISSUE THREAD

**Issue by wasaru** [Rainbox-dev/Duik#237]
When creating a 'Multiplan 2D' (french version), I'd like the new layers created to be named after the original layers, instead of L01, L02, L03...  (because, when dealing with several layers, it could be tricky to see wich ones are linked)
Also, I may love to choose which one would be used as the 'camera' layer.

I also have a question : Why can we adjust the layers number when applying the Multiplan 2D ? I don't get it, and when I wanted to try 3 layers (but having only 2 selected), it just crashed my After effects :)
thanks :)

**Comment by Nico-Duduf** [comment]
> When creating a 'Multiplan 2D' (french version), I'd like the new layers created to be named after the original layers, instead of L01, L02, L03... (because, when dealing with several layers, it could be tricky to see wich ones are linked)

good suggestion, will be done!

> Also, I may love to choose which one would be used as the 'camera' layer.

good suggestion too

> I also have a question : Why can we choose the layers when applying the Multiplan 2D ? I don't get it, and when I wanted to try 3 layers (but having only 2 selected), it just crashed my After effects :)
thanks :)

The number is used when there's no layer selected, to create the nulls without linking any layer. But it should not crash AE when there ARE layers selected ;)
will fix this

**Comment by wasaru** [comment]
thanks a lot !

it actually didn't crash AE totally, but the "viewport" was very messy, with reminiscences of the little white cameras (controller), and black areas... Even purging the whole memory didn't fix this, so I had to restart AE !  No big deal !

**Comment by Nico-Duduf** [comment]
Not sure this could be caused by Duik then. Can you send me the AEP for testing?
Moved this bug to a new issue for bugfix: #237

**Comment by oktomus** [comment]
Wanted to do it but the function doesn't seems to work. It fails when it tries to apply a preset.

**Comment by Nico-Duduf** [comment]
Here it works,
maybe you have to update your "presetEffects.xml" file in After Effects
Already patched files are available here: https://github.com/Rainbox-dev/Duik/tree/master/patched_presetEffects

**Comment by oktomus** [comment]
Right, thanks

**Comment by Nico-Duduf** [comment]
done!

@wasaru content ? Dispo dans quelques jours sur Duik 15.5
