### ISSUE TITLE
Removing "Scale Z-Link" 

### ISSUE THREAD

**Issue by wasaru** [Rainbox-dev/Duik#239]
I love the Scale Z-Link function in Duik !
I use it to position my layers in 3D space, and then I have to copy the scale (calculated by Duik),  remove the script and paste the scale.  Only after this can I animate the camera. (If I don't, the layers always keep their ratio, of course)
It's okay when I've got 2 or 3 layers, but with several layers, it's kind of boring :)

So I guess it would be pretty useful if there was the possibility to remove this Scale Z-function (ideally, by clicking again on the button, with the layers selected) so it remove the scripts and keep the calculated scale.

**Comment by Nico-Duduf** [comment]
great idea. Thanks.

**Comment by Nico-Duduf** [comment]
Great idea, thanks

**Comment by wasaru** [comment]
Additionally, there's something else that I would appreciate : 
As I sometime forget to convert my layers in 3D prior to apply the scale Z-link function, I click on "scale Z-link' with my '2D' layers selected and nothing happen, like if it worked (but it doesn't). 
So, it would be just cool if duik was notifying me something like  "you must select 3D layers to use this function"

**Comment by Nico-Duduf** [comment]
issue: #243

**Comment by oktomus** [comment]
I will try to do it today

**Comment by oktomus** [comment]
296e2b1
