### ISSUE TITLE
Turn layers to 3D when applying Scale Z-link

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#243]
As I sometime forget to convert my layers in 3D prior to apply the scale Z-link function, I click on "scale Z-link' with my '2D' layers selected and nothing happen, like if it worked (but it doesn't).
So, it would be just cool if duik was notifying me something like "you must select 3D layers to use this function"

Solution : automatically turn layers to 3D if they're 2D

**Comment by wasaru** [comment]
great!

**Comment by Nico-Duduf** [comment]
done

**Comment by wasaru** [comment]
No sooner said than done !
thx

**Comment by Nico-Duduf** [comment]
It will be available today in the 15.1 update
