### ISSUE TITLE
Onion skin bugs on previous/next frame buttons

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#247]
see
https://puu.sh/rkXdC/403b54db96.mp4

**Comment by kevinmasson** [comment]
J'ai pas très bien compris c'était quoi le soucis. J'ai un peu testé la fonctionnalité et j'ai eu du mal à comprendre comment ça marchait, pourtant je m'en suis pas mal servis sur Flash ^^

**Comment by Nico-Duduf** [comment]
j'avais pas vu ton message !

faudra que je fasse un ptit tuto sur cette fonction ;)

sinon, c'est fixed :)
