### ISSUE TITLE
[BUG] Paste Animation

### ISSUE THREAD

**Issue by Delfos1** [Rainbox-dev/Duik#265]
ERROR:
Can not set temporal ease. BEZIER interpolation required for ease, but not permitted for this property.
Line 2287

Looks like happens when the Rotation property in a shape layer is copied. It doesn't paste the keys.

**Comment by Nico-Duduf** [comment]
Thanks, I'll have a look at this

**Comment by Nico-Duduf** [comment]
will be fixed with  #338
