### ISSUE TITLE
Can not create 2 IK, Duik stops working after the first one (CC2017)

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#269]
see
http://forum.rainboxprod.coop/viewtopic.php?f=11&t=72

**Comment by kevinmasson** [comment]
Personnellement sur CC 2017 il y a beaucoup de choses qui ne fonctionnent pas, j'ai juste l'impression que le bouton valider ne fait rien.. Je vais faire des tests demain sur d'autre versions et m'assurer que ce n'est pas moi qui est cassé ma version de Duik :p

**Comment by Nico-Duduf** [comment]
Apparemment il y a pas mal de soucis avec CC2017, perso je n'utilise pas du tout cette version en prod, j'ai été bloqué par pas mal de merdouilles et préfère rester sur CC2015

Cela dit, je m'astreindrai un de ces 4 à y tester toutes les fonctionnalités de Duik voir si il y a pas d'autres trucs pétés dedans... Au moins pour garantir que la 16 fonctionnera sur CC2017

**Comment by kevinmasson** [comment]
Je vois ça ! 
Oui ce serait bien de faire ça pour la 16, mais je pense que ce sont juste des problèmes de UI, ils ont du arrêter le support sur l'ancienne façon de faire des Ui ?

**Comment by Nico-Duduf** [comment]
> ils ont du arrêter le support sur l'ancienne façon de faire des Ui ?

Pas à ma connaissance, mais la stabilité de scriptUI dans after a toujours été assez aléatoire, déjà avant l'introduction de CEP... Surtout au niveau des event (mouseover, mouseclick, etc) et de l'affichage de certains controles (genre les dropdowns...)

Plus on avance plus je me dis qu'on pourrait imaginer une legacy UI pour les gens sur CS6/CC et une UI CEP pour CC2014+ ; j'ai déjà déplacé la très grosse majorité des features dans libduik pour anticiper ce travail de séparation UI/features depuis Duik15. Je pense que Duik16 sera probablement la dernière version avec une UI "à l'ancienne", les utilisateurs encore sur CS6 diminuent progressivement...

**Comment by kevinmasson** [comment]
Cool ! J'espère juste que D16 fonctionnera bien sur CC2017

**Comment by Nico-Duduf** [comment]
I can't reproduce this bug on my own After Effects, anyone else still noticing this ?

**Comment by Nico-Duduf** [comment]
no news, let's remove the milestone on this one, won't fix for now
