### ISSUE TITLE
Goal doesn't work if there are keyframes on the rotation property

### ISSUE THREAD

**Issue by Delfos1** [Rainbox-dev/Duik#270]
> Can not set setValue() on a property with keyframes. Use setValueAtTime() or setValueAtKey() instead.

Line 5582

Happens when using a Goal on a layer with already existing rotation keyframes.
It works anyway (although is necessary to re-locate the existing keys due to the goal applied... but that's kind of expected anyway).

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, I'll fix this in the next update

**Comment by Nico-Duduf** [comment]
have to offset all the rotation keyframes for the goal to work while keeping the existing animation

**Comment by Nico-Duduf** [comment]
fixed in Duik 15.5, available in a few days
