### ISSUE TITLE
Connector: Detect if same comp to use "thisComp" in expression instead of "comp('name')"

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#277]

**Comment by kevinmasson** [comment]
J'aimerais bien donner un coup demain, pourrais tu donner le bloc de code correspondant ?

**Comment by Nico-Duduf** [comment]
Il faudrait que je regarde, mais de mémoire il me semble que c'est soit 
dans le fichier "duik_connector.jsx" du dossier tests, soit que c'est 
via une fonction dans libduik.jsxinc directement, qui doit s'appeler 
pickwhip !

**Comment by kevinmasson** [comment]
Ok je vais essayer de jeter un œil mais je ne promet rien !

**Comment by kevinmasson** [comment]
J'ai trouvé la fonction mais pas de rapport avec le titre de l'issue.. Ça ne doit pas être ici.

**Comment by Nico-Duduf** [comment]
Au temps pour moi,
Après avoir jeté un oeil au code, c'est (un peu) plus chiant que ça n'y parait.

Duik connector appelle dans libDuik la fonction `Duik.utils.getExpressionLink(prop)` pour générer le lien, qui n'est pas stocké dans une variable mais dans un champ de texte : `masterEdit.text`
le début de ce texte est donc toujours "comp('name')" où name est le nom de la comp qui contient le maître.

Ce qu'il faudrait faire, c'est que dans la fonction quand on valide
`applyButtonClicked()`
il faut vérifier d'abord si les propriétés sélectionnées sont dans la même comp que le maître (en checkant via le nom de la compo) et dans ce cas, remplacer "comp('name')" par "thisComp" dans le lien utilisé par generateExpression() (c'est facile, c'est tout ce qui est avant le premier "." dans la string)
(et uniquement là, faut garder "comp('name')" dans le champ de texte au cas où l'utilisateur veut faire une autre connexion dans une autre comp - peut être filer l'info en argument à generateExpression)

Bon sinon, en fait, au lieu de tout faire à partir d'une string gardée dans l'UI, faudrait peut être retaper un peu le truc pour garder une variable avec la propriété qui va servir de maître ; plus simple pour checker la comp où est la propriété (Duik.utils.getPropertyComp(prop) fait ça), et regénérer le lien correctement quand on veut. Dans l'interface comme ça, au lieu d'afficher un lien pas clair, on pourrait mettre un truc plus "user friendly"...

J'sais pas si je suis clair, il est tôt ^^ (11h22 oui.)

**Comment by Nico-Duduf** [comment]
C'est fait!
Reste à améliorer l'affichage dans l'interface, mais je ferai ça lors de l'intégration à Duik16

**Comment by kevinmasson** [comment]
Cool, je ne comprends encore pas tout mais ça va venir :p

**Comment by Nico-Duduf** [comment]
Normal, sur des outils que jai développé pour moi et documentés nulle part ;)

Faut que je commence un peu a ranger les choses et documenter les features (et le code) et ne plus être le seul à en connaitre les subtilités ;)
C'est un travail qu'on a commencé avec l'écriture du manuel puis en commençant les tutos, et aussi en commençant a cleaner le code et le ranger dans libduik...
