### ISSUE TITLE
Optimize launch time

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#281]
- [x] Test libduik.jsxinc loading time https://github.com/Rainbox-dev/Duik/blob/master/Duik.jsx#L178 (tested: a few ms)
- [x] Test icons creation time https://github.com/Rainbox-dev/Duik/blob/master/Duik.jsx#L350 (tested: 25ms)
- [x] Test UI creation time https://github.com/Rainbox-dev/Duik/blob/master/Duik.jsx#L3860 (tested: ~1000ms)

It's the UI which takes a lot of time to load, even without any icon/image.
Have to run some tests and keep this in mind when re-designing the UI for Duik 16

**Comment by kevinmasson** [comment]
I tested `#include 'libduik.jsxinc'`, the time taken is around **3ms**. Fast to enough to don't care about it ! 😃

**Comment by kevinmasson** [comment]
For the icons creation time, it's arround 25ms, still nothing to worry about.

**Comment by kevinmasson** [comment]
And finally, **for the UI**, it's arround **1000ms**, which is very long for just an UI, and there some parts that I didn't added in the time process, like the last call that shows the pannel. So it would be great to go under 400ms for something reactive.

For the whole `Duik.jsx` file, it's arround **1600ms** !!

**Comment by kevinmasson** [comment]
If you want to check the time on your own, you can use the same code that I used [here](https://github.com/kevinmasson/Duik/commit/9505a9bf8af382b5525c994532bfe1969f3b92da).

**Comment by Nico-Duduf** [comment]
UI takes 1000ms too here...
I tried removing all icons, and it does not speed up the process. I think it's AE itself which takes a lot of time to build the UI ; I'll keep this in mind when re-designing the UI for Duik16, trying to find which controls are faster to load, and limit the total number of objects.

**Comment by kevinmasson** [comment]
You're probably right, maybe we could do a millestone just to develop a parrallel UI ? I could make some research and if you want to, and then I could rebuild a small part of the UI (with the new features of script) on another Duik file (just to be sure to keep things working). Like this, you can still provide a new version of Duik and prepare the new interface.

Are the features and datas seperated from the interface ? If not, that would be great to use the MVC pattern design.

**Comment by Nico-Duduf** [comment]
as I've said in #269 I've begun to separate features and data from UI

We could create a new Duik_new_ui file, but I think it's too early to really develop a new UI, as there will be a lot of new features in Duik16 after the crowdfunding campaign to include in the UI. What we can do is try and test some other ways of designing the UI to try to make it lighter.

In Dugr.jsx https://github.com/Rainbox-dev/Dugr I used another way of designing the UI, without using buttons, but images only, and implementing `onmouseover` and `onclick`
I think it's a good start to improve the current UI of Duik -> #177

**Comment by kevinmasson** [comment]
Ok great, I will have a look on Dugr :)
