### ISSUE TITLE
Too much languages in Duik language settings (UI)

### ISSUE THREAD

**Issue by kevinmasson** [Rainbox-dev/Duik#287]
![screenshot_1](https://cloud.githubusercontent.com/assets/4656466/23460042/632c2aea-fe83-11e6-97c8-14117ff2d65d.png)

Noticed on CC 2017
This be because Dutranslator.setLanguage is call 2 times for adding #234. 

What we should do is remove [this line (Duik_translations.jsxinc#L55)](https://github.com/Rainbox-dev/Duik/blob/master/Duik_translations.jsxinc#L55)
And add `Dutranslator.getAvailable();` ìnstead of [this line](https://github.com/Rainbox-dev/Duik/pull/286/commits/9aee6bd655377626a1043066d43d53e6abc821b2#diff-7d1879ad9ac88def51a637406a79c30fR54) in the last pull request

**Comment by Nico-Duduf** [comment]
I think we should remove the call to getAvailable in the translator https://github.com/Rainbox-dev/Duik/blob/master/Duik_translations.jsxinc#L64

And instead make sure this function is called from Duik once (and only once) when Duik loads

This way, we can make as any calls as we need to setLanguage.

(and I've just noticed that's what you meant anyway ^^)

**Comment by kevinmasson** [comment]
Ahah ^^ I do that today
