### ISSUE TITLE
Bug on adding an automation to a image key

### ISSUE THREAD

**Issue by apsylone** [Rainbox-dev/Duik#294]
Hi Duik !

Thanks for your awesome plugins :-)

I met a problem when I try to add an "automation" to an image key.

Look at the screenshot attached for more information about it.

Can you help me maybe ?

Thanks :-)
![capture d ecran 2017-03-15 a 10 48 52](https://cloud.githubusercontent.com/assets/2072877/23942630/32e75d60-096d-11e7-8a84-e7f19b8c32a6.png)

**Comment by Nico-Duduf** [comment]
This is a bug, some automations cannot be added when there already are some keyframes on the property.

A workaround is to cut the keyframes, add the automation, then paste the keyframes.

Sorry for this, it will be fixed soon

**Comment by apsylone** [comment]
Hi @Nico-Duduf !

Thanks for your answer. But it seems that the bug is also when adding the automation on empty keyframes. We've tried with new compo.
