### ISSUE TITLE
Expressions break when using app.project.autoFixExpressions()

### ISSUE THREAD

**Issue by aescripts** [Rainbox-dev/Duik#296]
`app.project.autoFixExpressions()` has a bug that ignores effect names written with single quotes,  ie: `effect('IK End')('Slider')`

Because DUIK writes it's effect reference with single quotes, all the expressions break when updating the name of an effect using a script and `app.project.autoFixExpressions()`

To fix this please use double quotes, ie: `effect("IK End")("Slider")`

**Comment by aescripts** [comment]
Btw, we have reported this bug to Adobe but considering the wide use of DUIK and the slow response of Adobe to fix issues it would be great if you guys could make this simple change.

**Comment by aescripts** [comment]
Please see this sample project and script for an example of this bug: http://share.aescripts.com/3i1l071F3O0I/download/

**Comment by Nico-Duduf** [comment]
Hi Lloyd, thanks for your feedback!

I'll fix this for the next update!

**Comment by Nico-Duduf** [comment]
Fixed, it will be available in duik15.5 in a few weeks
