### ISSUE TITLE
Expressions break when renaming effects

### ISSUE THREAD

**Issue by aescripts** [Rainbox-dev/Duik#297]
If you rename any DUIK effect the DUIK expressions break. This is because the effect references have single quotes instead of double quotes and an Adobe bug that fails to update them after the effect is renamed. The fix is to simply write the DUIK expressions using double quotes.

This screencast shows the issue: http://share.aescripts.com/2e3m32103B2h/

![screen recording 2017-03-17 at 11 36 am](https://cloud.githubusercontent.com/assets/4550190/24050699/0feda69e-0b06-11e7-8181-1fd371584f67.gif)

**Comment by Nico-Duduf** [comment]
-> #296
