### ISSUE TITLE
Duik 16 Bones: replace spaces with underscores

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Duik#302]
Not sure if this is really relevant, but that would be great when creating a bone to do this.
If I put `Jambe` and then create, I get `B_Jambe_1`

**Comment by Nico-Duduf** [comment]
Indeed, that would be more consistent with how the Controlers are named

**Comment by Nico-Duduf** [comment]
Actually I'm doing the opposite, removing underscores everywhere and using spaces. Feels more modern :)
