### ISSUE TITLE
Duik won't open

### ISSUE THREAD

**Issue by juancarlosgzrz** [Rainbox-dev/Duik#342]
When AE it's opened it displays: 

"unable to execute script at line 5642"   and it won't butch.

Had to go back to the previous version (15.2 works)

**Comment by Nico-Duduf** [comment]
Hi,
yes, there was a bug in the first upload of 15.5, sorry!
(see http://forum.rainboxprod.coop/viewtopic.php?f=11&t=147&sid=672eab9d5d7fa50da5211b2dbca2f506)

This (shoud be) is fixed, just download it again and reinstall.

If it still does not work, just tell me if you're on mac or windows, I may have uploaded the wrong file, I'm not sure... Sorry!
