### ISSUE TITLE
build Duik as a single file for release

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#346]
maybe develop tools like https://github.com/Rainbox-dev/Duik/blob/master/Utils/includeIncludes.jsx

to include jsxinc,
and develop a tool to include binaries

**Comment by eZioPan** [comment]
I think a compromise solution maybe drop duik.jsx in ScriptUI Panels, and move other .jsxinc file into sub-directory.
EG.
$ScriptUI Panels/Duik.jsx
$ScriptUI Panels/Duik/*.jsxinc

This construct may be a little easier for bug tracking, and make ScriptUI Panel a lot neat

**Comment by Nico-Duduf** [comment]
What I meant was build it as a single file only for release, but keep the separate files on the development version. I wrote some tools to automate the release build ;)

And a single file makes debugging easier, as sometimes the ExtendScript debugger gives only the line where the error happened, but not the file...

**Comment by Nico-Duduf** [comment]
done, tested, and working
