### ISSUE TITLE
Error from AE- line 1917

### ISSUE THREAD

**Issue by AndreaSchmitz** [Rainbox-dev/Duik#350]
I'm getting the error "Unable to execute script at line 1917. File or folder does not exist."  when I try to open the DUIK window. It's line 1655 for Dugr. I'm on a Mac, and it's at a company so I have to get authentication from IT, I didn't know if that might have anything to do with it. 

<img width="381" alt="screen shot 2017-06-06 at 2 40 46 pm" src="https://user-images.githubusercontent.com/29237176/26846791-d14c395c-4ac8-11e7-9f8d-369b15157b52.png">

**Comment by Nico-Duduf** [comment]
Hi,

It seems that for an obscure reason, After Effects/Duik do not have the needed permissions in your user data folder. This is really weird, but fixable ;)

With the finder, go to:

/Users/yourUserName/Library/Application Support

There check if a "Duduf" subfolder exists, and if not, create it.
Then, check its permissions (right click, then "read informations"). You should have read and write permissions on it, if not, you'll have to change this (maybe you'll have to get authentication from IT for this)

If the "Duduf" subfolder already existed, check inside if there are a "Duik" and "Dugr" folder, then check their permissions too.

This should fix the issue....

Those folders are needed to store some files, especially the icons of the buttons...
I'll change how Duik 16 handles this to try to avoid this kind of issue.

**Comment by Nico-Duduf** [comment]
Oh, and, are you using any script launcher to launch Duik?
This may cause some issues too

**Comment by Nico-Duduf** [comment]
Also if the problem was wrong permissions, you may have other issues with other softwares.
In that case, this may be useful:
http://blog.chron.com/techblog/2011/09/want-to-really-repair-permissions-on-your-mac-try-this/

(But you need an admin access)

**Comment by AndreaSchmitz** [comment]
Hey, so I did what you said (adding the folders and altering permissions in Application Support) and ran the installer and it didn't work, so I grabbed the contents of those folders from my personal laptop and emailed them over and put them in and now it works fine. 

For some reason it wouldn't generate the pngs for the button icons in those folders even when the folders already existed. But it looks like it's working now. Thank you so much! Duik is a lifesaver!

**Comment by Nico-Duduf** [comment]
Glad to know you find a way to make it work!

Can you still please run this script:
https://github.com/Rainbox-dev/Duik/raw/master/Utils/check_folder_objects.zip
(unzip it then in After Effects go to File>Scripts>Run Script...)

And send me a screenshot of the informations shown wehn running it?

This will help me know what went wrong and debug future versions of Duik.

Thanks!

**Comment by AndreaSchmitz** [comment]
Absolutely!

<img width="414" alt="screen shot 2017-06-08 at 10 39 22 am" src="https://user-images.githubusercontent.com/29237176/26935563-4e1a9150-4c3a-11e7-94e9-f041b7904ce0.png">

**Comment by neilmartin83** [comment]
Just to chime in - I'm also seeing this on 2 different systems I'm testing when the user is an Active Directory mobile account. I can confirm that this issue does not present with a regular local account.

Running AE 14.2.1.34

We are a university deploying DUIK in a lab environment where Macs are shared by multiple users. Our Macs are bound to Active Directory and use mobile accounts - users log in with their network credentials, the Mac then authenticates against the directory server and caches their account (user record/password) locally and creates them a home folder structure in /Users - so their files and folders are all stored locally (we do not do SMB/AFP network based home directories on Macs at all - that's another world of pain!). This should result in the same behaviour as a 100% local account - their home directory is in the same place.

A workaround is to copy the required files to "~/Library/Application Support" before running DUIK and I can do that by deploying them to another location, then having a script run at login which copies them over.

Here's a screenshot of the script that you provided to @AndreaSchmitz when run against an AD mobile account.

![image](https://user-images.githubusercontent.com/10920581/31991815-8e090136-b970-11e7-92e4-9fc279b92e47.png)

Here's another screenshot of the script provided when run against a regular local account:

![image](https://user-images.githubusercontent.com/10920581/31992819-45e71868-b973-11e7-81ff-1afb44f08d93.png)

Kind regards,

Neil.

**Comment by Nico-Duduf** [comment]
Hi Neil, many thanks for this useful feedback,
I'll find a way to make all of this easier in Duik 16...
