### ISSUE TITLE
Panel Layout problem

### ISSUE THREAD

**Issue by muhammedemre** [Rainbox-dev/Duik#353]
![1](https://user-images.githubusercontent.com/23727440/27007475-ab03ed1a-4e5d-11e7-9801-206fa6c56a5f.JPG)
![2](https://user-images.githubusercontent.com/23727440/27007476-ab3b8888-4e5d-11e7-9486-701b0ff1ea03.JPG)
![3](https://user-images.githubusercontent.com/23727440/27007477-ab3f8bb8-4e5d-11e7-994d-f6609b158490.JPG)

As you can see in the images, my duik panel layout is kinda weird. Any help would be appreciated

**Comment by Nico-Duduf** [comment]
Hi,

You'll have to update After Effects,
See http://forum.rainboxprod.coop/viewtopic.php?f=16&t=11
