### ISSUE TITLE
could assign UUID for every translation items?

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/Duik#356]
I just think is it possible assign every translation items a unique ID?
UUID could solve 3 problem I met during translation.

1. It could be very different word for different language, although it's the same English word in different place.
Such as "Set" could be both nonverbal and verbal in English, but in Chinese we use different word. In current solution, it seems we need to edit duik.jsx file to differentiate them, but other language translation may not need it. This could make conflicts.

2. If new feature add to Duik, or old feature modified, it's difficult for translators to locate new thing, and translate them.
As for now, I need to run Duik to locate any untranslated word, but I may not run through everything, then there could be something left. Also, search source code for untranslated thing seems impossible, as a few undone but most of them as been translated.

3. When old function remove from Duik, then it's hard for translator to delete corresponding translation. So the translation may be more and more difficult to maintain.

With UUID, we can know exactly what word we are translating, where it will be display. And  we could use translation program to run through UUID, to know what has been added/modified/delete fast and easily.

**Comment by Nico-Duduf** [comment]
Thanks for this suggestion, but with the translator here https://github.com/Rainbox-dev/Dutranslator we're working on a framework which will fix all those issues, keeping the same code in Duik which is very easy for development (we can just write the string we want in English and not bother with anything else)

The translation tool will be able to detect new or deleted strings in the source code, and ignore the ones which should not be translated.

For the same words in different places, we're using a "context" option

Anyway, it's a good idea that this framework should use UUID for the translations, I'm adding this to not forget it ;)

**Comment by Nico-Duduf** [comment]
By the way, you can download a working build of the translation tool here:
https://rainboxprod.coop/en/dutranslator-is-available/

**Comment by Nico-Duduf** [comment]
but this version does not updates with new strings from the source code yet
