### ISSUE TITLE
DUIK Manual Update Suggestion

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/Duik#367]
If user chooses manual update duik, that is, manually edit PresetEffects.xml, then in the manual instructor should first check PresetEffects.xml, whether there is already "DUIK PSEUDO EFFECTS" exist. And then display "Replace" or "Append" new script into PresetEffects.xml

**Comment by Nico-Duduf** [comment]
you're right, thanks for your feedback

**Comment by Nico-Duduf** [comment]
no more use of presetEffects.xml in Duik 16

**Comment by eZioPan** [comment]
May need a way to tell users clean old preseteffects entry?

**Comment by Nico-Duduf** [comment]
Yes, I plan to develop a "cleaner", like the installer, which will remove Duik15, clean preseteffects, and remove any temporary files.
I'll add a manual clean instructions too ;)
