### ISSUE TITLE
Unable to execute script at line 434. null is an object.

### ISSUE THREAD

**Issue by anematic** [Rainbox-dev/Duik#398]
Hi,

Wondering if you can shed some light....

For a while now myself and a friend have been getting this same error. Unable to execute script at line 434. null is an object. On his machine it currently just hangs on 'Please wait while Duik is doing it's magic' and never loads. Mine never gets past the error message. 

I have tried manually installing, reinstalling and a couple of suggestions about permissions etc, but nothing seems to work. 

We love Duik and are desperate to get it working again, but at the moment neither of us can access it. Can you offer any suggestions please? 

Thanks, 
Rach

**Comment by Nico-Duduf** [comment]
Hi,

Seems there's a bug with After Effects and network sessions on MacOS

see https://github.com/Rainbox-dev/Duik/issues/276

The easiest way to fix this if you can is using Duik on a local session or modify Duik.jsx as described in this other issue.

We're trying to fix this/find a workaround in the upcoming Duik 16, available in a few weeks/months.
