### ISSUE TITLE
Export AE Animation to CSS

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik#65]

**Comment by oktomus** [comment]
Wouldn't it be best to export in SVG animation ? Much more performance available I think

**Comment by Nico-Duduf** [comment]
I don't know the SVG specs, will have to do some research ;
BTW i'm not even sure CSS anim is useful, especially with bodymovin around ;)

this is an old issue, I haven't thought about it for a long time ^^

**Comment by oktomus** [comment]
So let's close it ?

**Comment by Nico-Duduf** [comment]
Let's say stand by for now ;)

**Comment by oktomus** [comment]
ok :)
